*.style.font-size: 22
*.*.style.font-size: 22

title: |md
  # Terraform resources (v0.3.6)
| {near: top-center}

direction: right


license_map
partial_license_map

privatelink_endpoint: {tooltip: Datasource only}
group: {tooltip: Group permissions as well}
group_partial_permissions
service_token: {tooltip: Permissions as well}
project_artefacts: {tooltip: For setting the project docs and source freshness}
job: {
  style: {
    fill: "#ACE1AF"
    stroke: green
  }
}

conns: Connections {
  bigquery_connection
  fabric_connection
  connection: {tooltip: Works for Snowflake, Redshift, Postgres and Databricks}
}

env_creds: Environment Credentials {
  grid-columns: 2
  databricks_credential
  snowflake_credential
  bigquery_credential
  fabric_credential
  postgres_credential: {tooltip: Is used for Redshift as well}
}

service_token -- project: can scope to {
  style: {
    stroke-dash: 3
  }
}
group -- project
group_partial_permissions -- project
user_groups -- group
user_groups -- group_partial_permissions
project -- environment
job -- environment
job -- environment_variable_job_override
notification -- job
partial_notification -- job
project_artefacts -- job

project_artefacts -- project
webhook -- job: triggered by {
  style: {
    stroke-dash: 3
  }
}
environment -- env_creds
project -- project_connection
project_connection -- conns
conns -- privatelink_endpoint
project -- project_repository
project_repository -- repository
environment -- environment_variable
environment -- extended_attributes

(job -- *)[*].style.stroke: green
(* -- job)[*].style.stroke: green
