// Code generated by dbtp codegen. DO NOT EDIT.
package commands

import (
	"context"
	"fmt"
	"strconv"

	dbtCli "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/cli"
	dbtcloud "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/dbt_cloud"
	"github.com/urfave/cli/v3"
)

// credentialRedshiftToRow converts a RedshiftCredential to a table row.
func credentialRedshiftToRow(r dbtcloud.RedshiftCredential) []string {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []string{
		idVal,
		r.DefaultSchema,
		"*****",
		strconv.Itoa(r.Project_Id),
		r.Username,
	}
}

// credentialRedshiftToKeyValue converts a RedshiftCredential to key-value pairs for detailed display.
func credentialRedshiftToKeyValue(r dbtcloud.RedshiftCredential) []dbtCli.KeyValue {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []dbtCli.KeyValue{
		{Key: "ID", Value: idVal},
		{Key: "Default Schema", Value: r.DefaultSchema},
		{Key: "Password", Value: "*****"},
		{Key: "Project ID", Value: strconv.Itoa(r.Project_Id)},
		{Key: "Username", Value: r.Username},
	}
}

// CredentialRedshiftCommands returns the "redshift" command group.
func CredentialRedshiftCommands() *cli.Command {
	return &cli.Command{
		Name:  "redshift",
		Usage: "Redshift credential resource",
		Commands: []*cli.Command{
			credentialRedshiftGetCommand(),
			credentialRedshiftCreateCommand(),
			credentialRedshiftUpdateCommand(),
			credentialRedshiftDeleteCommand(),
		},
	}
}

func credentialRedshiftGetCommand() *cli.Command {
	return &cli.Command{
		Name:  "get",
		Usage: "Get a redshift by ID",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			result, err := client.GetRedshiftCredential(int(cmd.Int("project-id")), int(cmd.Int("id")))
			if err != nil {
				return fmt.Errorf("failed to get redshift: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				dbtCli.PrintKeyValue(credentialRedshiftToKeyValue(*result))
			})
		},
	}
}

func credentialRedshiftCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create a new redshift",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID to create the Redshift credential in",
				Required: true,
			},
			&cli.StringFlag{
				Name:     "type",
				Usage:    "Type ",
				Required: true,
			},
			&cli.BoolFlag{
				Name:  "is-active",
				Usage: "Whether the Redshift credential is active",
			},
			&cli.StringFlag{
				Name:     "schema",
				Usage:    "Schema",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "num-threads",
				Usage:    "Number of threads to use",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "username",
				Usage: "The username for the Redshift account. ",
			},
			&cli.StringFlag{
				Name:  "password",
				Usage: "The password for the Redshift account",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}
			result, err := client.CreateRedshiftCredential(int(cmd.Int("project-id")), cmd.String("type"), cmd.Bool("is-active"), cmd.String("schema"), int(cmd.Int("num-threads")), cmd.String("username"), cmd.String("password"))
			if err != nil {
				return fmt.Errorf("failed to create redshift: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Redshift created successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialRedshiftToKeyValue(*result))
			})
		},
	}
}

func credentialRedshiftUpdateCommand() *cli.Command {
	return &cli.Command{
		Name:  "update",
		Usage: "Update an existing redshift",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "default-schema",
				Usage: "Default schema name",
			},
			&cli.StringFlag{
				Name:  "password",
				Usage: "The password for the Redshift account",
			},
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "Project ID to create the Redshift credential in",
			},
			&cli.StringFlag{
				Name:  "username",
				Usage: "The username for the Redshift account. ",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			id := int(cmd.Int("id"))

			existing, err := client.GetRedshiftCredential(int(cmd.Int("project-id")), id)
			if err != nil {
				return fmt.Errorf("failed to get redshift: %w", err)
			}
			if v := cmd.String("default-schema"); v != "" {
				existing.DefaultSchema = v
			}
			if v := cmd.String("password"); v != "" {
				existing.Password = v
			}
			if v := int(cmd.Int("project-id")); v != 0 {
				existing.Project_Id = v
			}
			if v := cmd.String("username"); v != "" {
				existing.Username = v
			}

			result, err := client.UpdateRedshiftCredential(int(cmd.Int("project-id")), id, *existing)
			if err != nil {
				return fmt.Errorf("failed to update redshift: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Redshift updated successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialRedshiftToKeyValue(*result))
			})
		},
	}
}

func credentialRedshiftDeleteCommand() *cli.Command {
	return &cli.Command{
		Name:  "delete",
		Usage: "Delete a redshift",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			_, err = client.DeleteCredential(strconv.Itoa(int(cmd.Int("id"))), strconv.Itoa(int(cmd.Int("project-id"))))
			if err != nil {
				return fmt.Errorf("failed to delete redshift: %w", err)
			}

			format := getFormat(cmd)
			if format == "json" || format == "yaml" {
				return dbtCli.FormatOutput(format, map[string]string{"status": "deleted"}, func() {})
			}

			fmt.Println(dbtCli.SuccessStyle().Render("Redshift deleted successfully!"))
			return nil
		},
	}
}
