// Code generated by dbtp codegen. DO NOT EDIT.
package commands

import (
	"context"
	"fmt"
	"strconv"

	dbtCli "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/cli"
	dbtcloud "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/dbt_cloud"
	"github.com/urfave/cli/v3"
)

// credentialSnowflakeToRow converts a SnowflakeCredential to a table row.
func credentialSnowflakeToRow(r dbtcloud.SnowflakeCredential) []string {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []string{
		idVal,
		r.Auth_Type,
		r.Database,
		"*****",
		"*****",
		"*****",
		strconv.Itoa(r.Project_Id),
		r.Role,
		r.Schema,
		r.User,
		r.Warehouse,
	}
}

// credentialSnowflakeToKeyValue converts a SnowflakeCredential to key-value pairs for detailed display.
func credentialSnowflakeToKeyValue(r dbtcloud.SnowflakeCredential) []dbtCli.KeyValue {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []dbtCli.KeyValue{
		{Key: "ID", Value: idVal},
		{Key: "Auth Type", Value: r.Auth_Type},
		{Key: "Database", Value: r.Database},
		{Key: "Password", Value: "*****"},
		{Key: "Private Key", Value: "*****"},
		{Key: "Private Key Passphrase", Value: "*****"},
		{Key: "Project ID", Value: strconv.Itoa(r.Project_Id)},
		{Key: "Role", Value: r.Role},
		{Key: "Schema", Value: r.Schema},
		{Key: "User", Value: r.User},
		{Key: "Warehouse", Value: r.Warehouse},
	}
}

// CredentialSnowflakeCommands returns the "snowflake" command group.
func CredentialSnowflakeCommands() *cli.Command {
	return &cli.Command{
		Name:  "snowflake",
		Usage: "Snowflake credential resource.",
		Commands: []*cli.Command{
			credentialSnowflakeGetCommand(),
			credentialSnowflakeCreateCommand(),
			credentialSnowflakeUpdateCommand(),
			credentialSnowflakeDeleteCommand(),
		},
	}
}

func credentialSnowflakeGetCommand() *cli.Command {
	return &cli.Command{
		Name:  "get",
		Usage: "Get a snowflake by ID",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			result, err := client.GetSnowflakeCredential(int(cmd.Int("project-id")), int(cmd.Int("id")))
			if err != nil {
				return fmt.Errorf("failed to get snowflake: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				dbtCli.PrintKeyValue(credentialSnowflakeToKeyValue(*result))
			})
		},
	}
}

func credentialSnowflakeCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create a new snowflake",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID to create the Snowflake credential in",
				Required: true,
			},
			&cli.StringFlag{
				Name:     "type",
				Usage:    "Type ",
				Required: true,
			},
			&cli.BoolFlag{
				Name:  "is-active",
				Usage: "Whether the Snowflake credential is active",
			},
			&cli.StringFlag{
				Name:  "database",
				Usage: "The catalog to connect use",
			},
			&cli.StringFlag{
				Name:  "role",
				Usage: "The role to assume",
			},
			&cli.StringFlag{
				Name:  "warehouse",
				Usage: "The warehouse to use",
			},
			&cli.StringFlag{
				Name:  "schema",
				Usage: "The schema where to create models. This is an optional field ONLY if the credential is used for Semantic Layer configuration, otherwise it is required.",
			},
			&cli.StringFlag{
				Name:  "user",
				Usage: "The username for the Snowflake account. This is an optional field ONLY if the credential is used for Semantic Layer configuration, otherwise it is required. ",
			},
			&cli.StringFlag{
				Name:  "password",
				Usage: "The password for the Snowflake account",
			},
			&cli.StringFlag{
				Name:  "private-key",
				Usage: "The private key for the Snowflake account",
			},
			&cli.StringFlag{
				Name:  "private-key-passphrase",
				Usage: "The passphrase for the private key",
			},
			&cli.StringFlag{
				Name:     "auth-type",
				Usage:    "The type of Snowflake credential ('password' or 'keypair')",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "num-threads",
				Usage:    "Number of threads to use",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}
			result, err := client.CreateSnowflakeCredential(int(cmd.Int("project-id")), cmd.String("type"), cmd.Bool("is-active"), cmd.String("database"), cmd.String("role"), cmd.String("warehouse"), cmd.String("schema"), cmd.String("user"), cmd.String("password"), cmd.String("private-key"), cmd.String("private-key-passphrase"), cmd.String("auth-type"), int(cmd.Int("num-threads")))
			if err != nil {
				return fmt.Errorf("failed to create snowflake: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Snowflake created successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialSnowflakeToKeyValue(*result))
			})
		},
	}
}

func credentialSnowflakeUpdateCommand() *cli.Command {
	return &cli.Command{
		Name:  "update",
		Usage: "Update an existing snowflake",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "auth-type",
				Usage: "The type of Snowflake credential ('password' or 'keypair')",
			},
			&cli.StringFlag{
				Name:  "database",
				Usage: "The catalog to connect use",
			},
			&cli.StringFlag{
				Name:  "password",
				Usage: "The password for the Snowflake account",
			},
			&cli.StringFlag{
				Name:  "private-key",
				Usage: "The private key for the Snowflake account",
			},
			&cli.StringFlag{
				Name:  "private-key-passphrase",
				Usage: "The passphrase for the private key",
			},
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "Project ID to create the Snowflake credential in",
			},
			&cli.StringFlag{
				Name:  "role",
				Usage: "The role to assume",
			},
			&cli.StringFlag{
				Name:  "schema",
				Usage: "The schema where to create models. This is an optional field ONLY if the credential is used for Semantic Layer configuration, otherwise it is required.",
			},
			&cli.StringFlag{
				Name:  "user",
				Usage: "The username for the Snowflake account. This is an optional field ONLY if the credential is used for Semantic Layer configuration, otherwise it is required. ",
			},
			&cli.StringFlag{
				Name:  "warehouse",
				Usage: "The warehouse to use",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			id := int(cmd.Int("id"))

			existing, err := client.GetSnowflakeCredential(int(cmd.Int("project-id")), id)
			if err != nil {
				return fmt.Errorf("failed to get snowflake: %w", err)
			}
			if v := cmd.String("auth-type"); v != "" {
				existing.Auth_Type = v
			}
			if v := cmd.String("database"); v != "" {
				existing.Database = v
			}
			if v := cmd.String("password"); v != "" {
				existing.Password = v
			}
			if v := cmd.String("private-key"); v != "" {
				existing.PrivateKey = v
			}
			if v := cmd.String("private-key-passphrase"); v != "" {
				existing.PrivateKeyPassphrase = v
			}
			if v := int(cmd.Int("project-id")); v != 0 {
				existing.Project_Id = v
			}
			if v := cmd.String("role"); v != "" {
				existing.Role = v
			}
			if v := cmd.String("schema"); v != "" {
				existing.Schema = v
			}
			if v := cmd.String("user"); v != "" {
				existing.User = v
			}
			if v := cmd.String("warehouse"); v != "" {
				existing.Warehouse = v
			}

			result, err := client.UpdateSnowflakeCredential(int(cmd.Int("project-id")), id, *existing)
			if err != nil {
				return fmt.Errorf("failed to update snowflake: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Snowflake updated successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialSnowflakeToKeyValue(*result))
			})
		},
	}
}

func credentialSnowflakeDeleteCommand() *cli.Command {
	return &cli.Command{
		Name:  "delete",
		Usage: "Delete a snowflake",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			_, err = client.DeleteCredential(strconv.Itoa(int(cmd.Int("id"))), strconv.Itoa(int(cmd.Int("project-id"))))
			if err != nil {
				return fmt.Errorf("failed to delete snowflake: %w", err)
			}

			format := getFormat(cmd)
			if format == "json" || format == "yaml" {
				return dbtCli.FormatOutput(format, map[string]string{"status": "deleted"}, func() {})
			}

			fmt.Println(dbtCli.SuccessStyle().Render("Snowflake deleted successfully!"))
			return nil
		},
	}
}
