// Code generated by dbtp codegen. DO NOT EDIT.
package commands

import (
	"context"
	"fmt"
	"strconv"

	dbtCli "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/cli"
	dbtcloud "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/dbt_cloud"
	"github.com/urfave/cli/v3"
)

// credentialPostgresToRow converts a PostgresCredential to a table row.
func credentialPostgresToRow(r dbtcloud.PostgresCredential) []string {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []string{
		idVal,
		r.Default_Schema,
		"*****",
		strconv.Itoa(r.Project_Id),
		r.Target_Name,
		r.Type,
		r.Username,
	}
}

// credentialPostgresToKeyValue converts a PostgresCredential to key-value pairs for detailed display.
func credentialPostgresToKeyValue(r dbtcloud.PostgresCredential) []dbtCli.KeyValue {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []dbtCli.KeyValue{
		{Key: "ID", Value: idVal},
		{Key: "Default Schema", Value: r.Default_Schema},
		{Key: "Password", Value: "*****"},
		{Key: "Project ID", Value: strconv.Itoa(r.Project_Id)},
		{Key: "Target Name", Value: r.Target_Name},
		{Key: "Type", Value: r.Type},
		{Key: "Username", Value: r.Username},
	}
}

// CredentialPostgresCommands returns the "postgres" command group.
func CredentialPostgresCommands() *cli.Command {
	return &cli.Command{
		Name:  "postgres",
		Usage: "Postgres credential resource.",
		Commands: []*cli.Command{
			credentialPostgresGetCommand(),
			credentialPostgresCreateCommand(),
			credentialPostgresUpdateCommand(),
			credentialPostgresDeleteCommand(),
		},
	}
}

func credentialPostgresGetCommand() *cli.Command {
	return &cli.Command{
		Name:  "get",
		Usage: "Get a postgres by ID",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			result, err := client.GetPostgresCredential(int(cmd.Int("project-id")), int(cmd.Int("id")))
			if err != nil {
				return fmt.Errorf("failed to get postgres: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				dbtCli.PrintKeyValue(credentialPostgresToKeyValue(*result))
			})
		},
	}
}

func credentialPostgresCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create a new postgres",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID to create the Postgres/Redshift/AlloyDB credential in.",
				Required: true,
			},
			&cli.BoolFlag{
				Name:  "is-active",
				Usage: "Whether the Postgres/Redshift/AlloyDB credential is active",
			},
			&cli.StringFlag{
				Name:  "type",
				Usage: "Type of connection. One of (postgres/redshift). Use postgres for alloydb connections. Optional only when semantic_layer_credential is set to true; otherwise, this field is required.",
			},
			&cli.StringFlag{
				Name:  "default-schema",
				Usage: "Default schema name. Optional only when semantic_layer_credential is set to true; otherwise, this field is required.",
			},
			&cli.StringFlag{
				Name:  "target-name",
				Usage: "Default schema name",
			},
			&cli.StringFlag{
				Name:     "username",
				Usage:    "Username for Postgres/Redshift/AlloyDB",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "password",
				Usage: "Password for Postgres/Redshift/AlloyDB",
			},
			&cli.IntFlag{
				Name:  "num-threads",
				Usage: "Number of threads to use (required for Redshift)",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}
			result, err := client.CreatePostgresCredential(int(cmd.Int("project-id")), cmd.Bool("is-active"), cmd.String("type"), cmd.String("default-schema"), cmd.String("target-name"), cmd.String("username"), cmd.String("password"), int(cmd.Int("num-threads")))
			if err != nil {
				return fmt.Errorf("failed to create postgres: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Postgres created successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialPostgresToKeyValue(*result))
			})
		},
	}
}

func credentialPostgresUpdateCommand() *cli.Command {
	return &cli.Command{
		Name:  "update",
		Usage: "Update an existing postgres",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "default-schema",
				Usage: "Default schema name. Optional only when semantic_layer_credential is set to true; otherwise, this field is required.",
			},
			&cli.StringFlag{
				Name:  "password",
				Usage: "Password for Postgres/Redshift/AlloyDB",
			},
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "Project ID to create the Postgres/Redshift/AlloyDB credential in.",
			},
			&cli.StringFlag{
				Name:  "target-name",
				Usage: "Default schema name",
			},
			&cli.StringFlag{
				Name:  "type",
				Usage: "Type of connection. One of (postgres/redshift). Use postgres for alloydb connections. Optional only when semantic_layer_credential is set to true; otherwise, this field is required.",
			},
			&cli.StringFlag{
				Name:  "username",
				Usage: "Username for Postgres/Redshift/AlloyDB",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			id := int(cmd.Int("id"))

			existing, err := client.GetPostgresCredential(int(cmd.Int("project-id")), id)
			if err != nil {
				return fmt.Errorf("failed to get postgres: %w", err)
			}
			if v := cmd.String("default-schema"); v != "" {
				existing.Default_Schema = v
			}
			if v := cmd.String("password"); v != "" {
				existing.Password = v
			}
			if v := int(cmd.Int("project-id")); v != 0 {
				existing.Project_Id = v
			}
			if v := cmd.String("target-name"); v != "" {
				existing.Target_Name = v
			}
			if v := cmd.String("type"); v != "" {
				existing.Type = v
			}
			if v := cmd.String("username"); v != "" {
				existing.Username = v
			}

			result, err := client.UpdatePostgresCredential(int(cmd.Int("project-id")), id, *existing)
			if err != nil {
				return fmt.Errorf("failed to update postgres: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Postgres updated successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialPostgresToKeyValue(*result))
			})
		},
	}
}

func credentialPostgresDeleteCommand() *cli.Command {
	return &cli.Command{
		Name:  "delete",
		Usage: "Delete a postgres",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			_, err = client.DeletePostgresCredential(strconv.Itoa(int(cmd.Int("id"))), strconv.Itoa(int(cmd.Int("project-id"))))
			if err != nil {
				return fmt.Errorf("failed to delete postgres: %w", err)
			}

			format := getFormat(cmd)
			if format == "json" || format == "yaml" {
				return dbtCli.FormatOutput(format, map[string]string{"status": "deleted"}, func() {})
			}

			fmt.Println(dbtCli.SuccessStyle().Render("Postgres deleted successfully!"))
			return nil
		},
	}
}
