// Code generated by dbtp codegen. DO NOT EDIT.
package commands

import (
	"context"
	"fmt"
	"strconv"

	dbtCli "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/cli"
	dbtcloud "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/dbt_cloud"
	"github.com/urfave/cli/v3"
)

// credentialBigqueryToRow converts a BigQueryCredential to a table row.
func credentialBigqueryToRow(r dbtcloud.BigQueryCredential) []string {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []string{
		idVal,
		strconv.Itoa(r.Project_Id),
	}
}

// credentialBigqueryToKeyValue converts a BigQueryCredential to key-value pairs for detailed display.
func credentialBigqueryToKeyValue(r dbtcloud.BigQueryCredential) []dbtCli.KeyValue {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	return []dbtCli.KeyValue{
		{Key: "ID", Value: idVal},
		{Key: "Project ID", Value: strconv.Itoa(r.Project_Id)},
	}
}

// CredentialBigqueryCommands returns the "bigquery" command group.
func CredentialBigqueryCommands() *cli.Command {
	return &cli.Command{
		Name:  "bigquery",
		Usage: "Bigquery credential resource",
		Commands: []*cli.Command{
			credentialBigqueryGetCommand(),
			credentialBigqueryCreateCommand(),
			credentialBigqueryUpdateCommand(),
			credentialBigqueryDeleteCommand(),
		},
	}
}

func credentialBigqueryGetCommand() *cli.Command {
	return &cli.Command{
		Name:  "get",
		Usage: "Get a bigquery by ID",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			result, err := client.GetBigQueryCredential(int(cmd.Int("project-id")), int(cmd.Int("id")))
			if err != nil {
				return fmt.Errorf("failed to get bigquery: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				dbtCli.PrintKeyValue(credentialBigqueryToKeyValue(*result))
			})
		},
	}
}

func credentialBigqueryCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create a new bigquery",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID to create the BigQuery credential in",
				Required: true,
			},
			&cli.StringFlag{
				Name:     "type",
				Usage:    "Type ",
				Required: true,
			},
			&cli.BoolFlag{
				Name:  "is-active",
				Usage: "Whether the BigQuery credential is active",
			},
			&cli.StringFlag{
				Name:     "dataset",
				Usage:    "Default dataset name",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "num-threads",
				Usage:    "Number of threads to use",
				Required: true,
			},
			&cli.StringFlag{
				Name:     "adapter-version",
				Usage:    "Adapter Version",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}
			result, err := client.CreateBigQueryCredential(int(cmd.Int("project-id")), cmd.String("type"), cmd.Bool("is-active"), cmd.String("dataset"), int(cmd.Int("num-threads")), cmd.String("adapter-version"))
			if err != nil {
				return fmt.Errorf("failed to create bigquery: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Bigquery created successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialBigqueryToKeyValue(*result))
			})
		},
	}
}

func credentialBigqueryUpdateCommand() *cli.Command {
	return &cli.Command{
		Name:  "update",
		Usage: "Update an existing bigquery",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "Project ID to create the BigQuery credential in",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			id := int(cmd.Int("id"))

			existing, err := client.GetBigQueryCredential(int(cmd.Int("project-id")), id)
			if err != nil {
				return fmt.Errorf("failed to get bigquery: %w", err)
			}
			if v := int(cmd.Int("project-id")); v != 0 {
				existing.Project_Id = v
			}

			result, err := client.UpdateBigQueryCredential(int(cmd.Int("project-id")), id, *existing)
			if err != nil {
				return fmt.Errorf("failed to update bigquery: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Bigquery updated successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(credentialBigqueryToKeyValue(*result))
			})
		},
	}
}

func credentialBigqueryDeleteCommand() *cli.Command {
	return &cli.Command{
		Name:  "delete",
		Usage: "Delete a bigquery",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Credential ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			_, err = client.DeleteCredential(strconv.Itoa(int(cmd.Int("id"))), strconv.Itoa(int(cmd.Int("project-id"))))
			if err != nil {
				return fmt.Errorf("failed to delete bigquery: %w", err)
			}

			format := getFormat(cmd)
			if format == "json" || format == "yaml" {
				return dbtCli.FormatOutput(format, map[string]string{"status": "deleted"}, func() {})
			}

			fmt.Println(dbtCli.SuccessStyle().Render("Bigquery deleted successfully!"))
			return nil
		},
	}
}
