// Code generated by dbtp codegen. DO NOT EDIT.
package commands

import (
	"context"
	"fmt"
	"strconv"

	dbtCli "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/cli"
	dbtcloud "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/dbt_cloud"
	"github.com/urfave/cli/v3"
)

// environmentToRow converts a Environment to a table row.
func environmentToRow(r dbtcloud.Environment) []string {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	connectionidVal := ""
	if r.ConnectionID != nil {
		connectionidVal = strconv.Itoa(*r.ConnectionID)
	}
	custom_branchVal := ""
	if r.Custom_Branch != nil {
		custom_branchVal = *r.Custom_Branch
	}
	deploymenttypeVal := ""
	if r.DeploymentType != nil {
		deploymenttypeVal = *r.DeploymentType
	}
	extendedattributesidVal := ""
	if r.ExtendedAttributesID != nil {
		extendedattributesidVal = strconv.Itoa(*r.ExtendedAttributesID)
	}
	primaryprofileidVal := ""
	if r.PrimaryProfileID != nil {
		primaryprofileidVal = strconv.Itoa(*r.PrimaryProfileID)
	}
	return []string{
		idVal,
		r.Name,
		connectionidVal,
		custom_branchVal,
		r.Dbt_Version,
		deploymenttypeVal,
		strconv.FormatBool(r.EnableModelQueryHistory),
		extendedattributesidVal,
		primaryprofileidVal,
		strconv.Itoa(r.Project_Id),
		r.Type,
		strconv.FormatBool(r.Use_Custom_Branch),
	}
}

// environmentToKeyValue converts a Environment to key-value pairs for detailed display.
func environmentToKeyValue(r dbtcloud.Environment) []dbtCli.KeyValue {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	connectionidVal := ""
	if r.ConnectionID != nil {
		connectionidVal = strconv.Itoa(*r.ConnectionID)
	}
	custom_branchVal := ""
	if r.Custom_Branch != nil {
		custom_branchVal = *r.Custom_Branch
	}
	deploymenttypeVal := ""
	if r.DeploymentType != nil {
		deploymenttypeVal = *r.DeploymentType
	}
	extendedattributesidVal := ""
	if r.ExtendedAttributesID != nil {
		extendedattributesidVal = strconv.Itoa(*r.ExtendedAttributesID)
	}
	primaryprofileidVal := ""
	if r.PrimaryProfileID != nil {
		primaryprofileidVal = strconv.Itoa(*r.PrimaryProfileID)
	}
	return []dbtCli.KeyValue{
		{Key: "ID", Value: idVal},
		{Key: "Name", Value: r.Name},
		{Key: "Connection ID", Value: connectionidVal},
		{Key: "Custom Branch", Value: custom_branchVal},
		{Key: "dbt Version", Value: r.Dbt_Version},
		{Key: "Deployment Type", Value: deploymenttypeVal},
		{Key: "Enable Model Query History", Value: strconv.FormatBool(r.EnableModelQueryHistory)},
		{Key: "Extended Attributes ID", Value: extendedattributesidVal},
		{Key: "Primary Profile ID", Value: primaryprofileidVal},
		{Key: "Project ID", Value: strconv.Itoa(r.Project_Id)},
		{Key: "Type", Value: r.Type},
		{Key: "Use Custom Branch", Value: strconv.FormatBool(r.Use_Custom_Branch)},
	}
}

// EnvironmentCommands returns the "environment" command group.
func EnvironmentCommands() *cli.Command {
	return &cli.Command{
		Name:  "environment",
		Usage: "Resource to manage dbt Cloud environments for the different dbt Cloud projects.",
		Commands: []*cli.Command{
			environmentGetCommand(),
			environmentListCommand(),
			environmentCreateCommand(),
			environmentUpdateCommand(),
			environmentDeleteCommand(),
		},
	}
}

func environmentGetCommand() *cli.Command {
	return &cli.Command{
		Name:  "get",
		Usage: "Get a environment by ID",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Environment ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			result, err := client.GetEnvironment(int(cmd.Int("project-id")), int(cmd.Int("id")))
			if err != nil {
				return fmt.Errorf("failed to get environment: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				dbtCli.PrintKeyValue(environmentToKeyValue(*result))
			})
		},
	}
}

func environmentListCommand() *cli.Command {
	return &cli.Command{
		Name:  "list",
		Usage: "List environments",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "The project ID to filter the environments for [Optional]",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {

			client, err := getClient()
			if err != nil {
				return err
			}
			items, err := client.GetAllEnvironments(int(cmd.Int("project-id")))
			if err != nil {
				return fmt.Errorf("failed to list environments: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, items, func() {
				headers := []string{"ID", "Name", "Connection ID", "Custom Branch", "dbt Version", "Deployment Type", "Enable Model Query History", "Extended Attributes ID", "Primary Profile ID", "Project ID", "Type", "Use Custom Branch"}
				rows := make([][]string, 0, len(items))
				for _, item := range items {
					rows = append(rows, environmentToRow(item))
				}
				dbtCli.PrintTable(headers, rows)
			})
		},
	}
}

func environmentCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create a new environment",
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name:  "is-active",
				Usage: "Whether the environment is active",
			},
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID to create the environment in",
				Required: true,
			},
			&cli.StringFlag{
				Name:     "name",
				Usage:    "The name of the environment",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "dbt-version",
				Usage: "Version number of dbt to use in this environment. It needs to be in the format `major.minor.0-latest` (e.g. `1.5.0-latest`), `major.minor.0-pre`, `compatible`, `extended`, `versionless`, `latest` or `latest-fusion`. While `versionless` is still supported, using `latest` is recommended. Defaults to `latest` if no version is provided",
			},
			&cli.StringFlag{
				Name:     "type",
				Usage:    "The type of environment (must be either development or deployment)",
				Required: true,
			},
			&cli.BoolFlag{
				Name:  "use-custom-branch",
				Usage: "Whether to use a custom git branch in this environment",
			},
			&cli.StringFlag{
				Name:  "custom-branch",
				Usage: "The custom branch name to use",
			},
			&cli.IntFlag{
				Name:  "credential-id",
				Usage: "The Credential ID for this environment. A credential is not actionable for development environments, as users have to set their own development credentials in dbt Cloud.",
			},
			&cli.StringFlag{
				Name:  "deployment-type",
				Usage: "The type of environment. Only valid for environments of type 'deployment' and for now can only be 'production', 'staging' or left empty for generic environments",
			},
			&cli.IntFlag{
				Name:  "extended-attributes-id",
				Usage: "The ID of the extended attributes applied",
			},
			&cli.IntFlag{
				Name:  "connection-id",
				Usage: "A connection ID (used with Global Connections)",
			},
			&cli.BoolFlag{
				Name:  "enable-model-query-history",
				Usage: "Whether to enable model query history in this environment. As of Oct 2024, works only for Snowflake and BigQuery.",
			},
			&cli.IntFlag{
				Name:  "primary-profile-id",
				Usage: "The ID of the primary profile for this environment. A profile ties together a connection and credentials. Only applicable to deployment environments. ~> Setting `primary_profile_id` alongside `connection_id`, `credential_id`, or `extended_attributes_id` will produce an error. When a profile is assigned, the API determines those values from the profile. Manage connection, credentials, and extended attributes through the `dbtcloud_profile` resource instead.",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}
			result, err := client.CreateEnvironment(cmd.Bool("is-active"), int(cmd.Int("project-id")), cmd.String("name"), cmd.String("dbt-version"), cmd.String("type"), cmd.Bool("use-custom-branch"), cmd.String("custom-branch"), int(cmd.Int("credential-id")), cmd.String("deployment-type"), int(cmd.Int("extended-attributes-id")), int(cmd.Int("connection-id")), cmd.Bool("enable-model-query-history"), int(cmd.Int("primary-profile-id")))
			if err != nil {
				return fmt.Errorf("failed to create environment: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Environment created successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(environmentToKeyValue(*result))
			})
		},
	}
}

func environmentUpdateCommand() *cli.Command {
	return &cli.Command{
		Name:  "update",
		Usage: "Update an existing environment",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Environment ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:  "connection-id",
				Usage: "A connection ID (used with Global Connections)",
			},
			&cli.StringFlag{
				Name:  "custom-branch",
				Usage: "The custom branch name to use",
			},
			&cli.StringFlag{
				Name:  "dbt-version",
				Usage: "Version number of dbt to use in this environment. It needs to be in the format `major.minor.0-latest` (e.g. `1.5.0-latest`), `major.minor.0-pre`, `compatible`, `extended`, `versionless`, `latest` or `latest-fusion`. While `versionless` is still supported, using `latest` is recommended. Defaults to `latest` if no version is provided",
			},
			&cli.StringFlag{
				Name:  "deployment-type",
				Usage: "The type of environment. Only valid for environments of type 'deployment' and for now can only be 'production', 'staging' or left empty for generic environments",
			},
			&cli.BoolFlag{
				Name:  "enable-model-query-history",
				Usage: "Whether to enable model query history in this environment. As of Oct 2024, works only for Snowflake and BigQuery.",
			},
			&cli.IntFlag{
				Name:  "extended-attributes-id",
				Usage: "The ID of the extended attributes applied",
			},
			&cli.StringFlag{
				Name:  "name",
				Usage: "The name of the environment",
			},
			&cli.IntFlag{
				Name:  "primary-profile-id",
				Usage: "The ID of the primary profile for this environment. A profile ties together a connection and credentials. Only applicable to deployment environments. ~> Setting `primary_profile_id` alongside `connection_id`, `credential_id`, or `extended_attributes_id` will produce an error. When a profile is assigned, the API determines those values from the profile. Manage connection, credentials, and extended attributes through the `dbtcloud_profile` resource instead.",
			},
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "Project ID to create the environment in",
			},
			&cli.StringFlag{
				Name:  "type",
				Usage: "The type of environment (must be either development or deployment)",
			},
			&cli.BoolFlag{
				Name:  "use-custom-branch",
				Usage: "Whether to use a custom git branch in this environment",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			id := int(cmd.Int("id"))

			existing, err := client.GetEnvironment(int(cmd.Int("project-id")), id)
			if err != nil {
				return fmt.Errorf("failed to get environment: %w", err)
			}
			if cmd.IsSet("connection-id") {
				v := int(cmd.Int("connection-id"))
				existing.ConnectionID = &v
			}
			if cmd.IsSet("custom-branch") {
				v := cmd.String("custom-branch")
				existing.Custom_Branch = &v
			}
			if v := cmd.String("dbt-version"); v != "" {
				existing.Dbt_Version = v
			}
			if cmd.IsSet("deployment-type") {
				v := cmd.String("deployment-type")
				existing.DeploymentType = &v
			}
			if cmd.IsSet("enable-model-query-history") {
				existing.EnableModelQueryHistory = cmd.Bool("enable-model-query-history")
			}
			if cmd.IsSet("extended-attributes-id") {
				v := int(cmd.Int("extended-attributes-id"))
				existing.ExtendedAttributesID = &v
			}
			if v := cmd.String("name"); v != "" {
				existing.Name = v
			}
			if cmd.IsSet("primary-profile-id") {
				v := int(cmd.Int("primary-profile-id"))
				existing.PrimaryProfileID = &v
			}
			if v := int(cmd.Int("project-id")); v != 0 {
				existing.Project_Id = v
			}
			if v := cmd.String("type"); v != "" {
				existing.Type = v
			}
			if cmd.IsSet("use-custom-branch") {
				existing.Use_Custom_Branch = cmd.Bool("use-custom-branch")
			}

			result, err := client.UpdateEnvironment(int(cmd.Int("project-id")), id, *existing)
			if err != nil {
				return fmt.Errorf("failed to update environment: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Environment updated successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(environmentToKeyValue(*result))
			})
		},
	}
}

func environmentDeleteCommand() *cli.Command {
	return &cli.Command{
		Name:  "delete",
		Usage: "Delete a environment",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Environment ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			_, err = client.DeleteEnvironment(int(cmd.Int("project-id")), int(cmd.Int("id")))
			if err != nil {
				return fmt.Errorf("failed to delete environment: %w", err)
			}

			format := getFormat(cmd)
			if format == "json" || format == "yaml" {
				return dbtCli.FormatOutput(format, map[string]string{"status": "deleted"}, func() {})
			}

			fmt.Println(dbtCli.SuccessStyle().Render("Environment deleted successfully!"))
			return nil
		},
	}
}
