// Code generated by dbtp codegen. DO NOT EDIT.
package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	dbtCli "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/cli"
	dbtcloud "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/dbt_cloud"
	"github.com/urfave/cli/v3"
)

// jobToRow converts a JobWithEnvironment to a table row.
func jobToRow(r dbtcloud.JobWithEnvironment) []string {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	dbtversionVal := ""
	if r.DbtVersion != nil {
		dbtversionVal = *r.DbtVersion
	}
	deferringenvironmentidVal := ""
	if r.DeferringEnvironmentId != nil {
		deferringenvironmentidVal = strconv.Itoa(*r.DeferringEnvironmentId)
	}
	executionBytes, _ := json.Marshal(r.Execution)
	executionJSON := string(executionBytes)
	forcenodeselectionVal := ""
	if r.ForceNodeSelection != nil {
		forcenodeselectionVal = strconv.FormatBool(*r.ForceNodeSelection)
	}
	jobcompletiontriggerBytes, _ := json.Marshal(r.JobCompletionTrigger)
	jobcompletiontriggerJSON := string(jobcompletiontriggerBytes)
	triggersBytes, _ := json.Marshal(r.Triggers)
	triggersJSON := string(triggersBytes)
	return []string{
		idVal,
		r.Name,
		r.Description,
		r.CompareChangesFlags,
		dbtversionVal,
		deferringenvironmentidVal,
		strconv.Itoa(r.EnvironmentId),
		strconv.FormatBool(r.ErrorsOnLintFailure),
		strings.Join(r.ExecuteSteps, ", "),
		executionJSON,
		forcenodeselectionVal,
		strconv.FormatBool(r.GenerateDocs),
		jobcompletiontriggerJSON,
		r.JobType,
		strconv.Itoa(r.ProjectId),
		strconv.FormatBool(r.RunCompareChanges),
		strconv.FormatBool(r.RunGenerateSources),
		strconv.FormatBool(r.RunLint),
		triggersJSON,
		strconv.FormatBool(r.TriggersOnDraftPR),
	}
}

// jobToKeyValue converts a Job to key-value pairs for detailed display.
func jobToKeyValue(r dbtcloud.Job) []dbtCli.KeyValue {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	dbtversionVal := ""
	if r.DbtVersion != nil {
		dbtversionVal = *r.DbtVersion
	}
	deferringenvironmentidVal := ""
	if r.DeferringEnvironmentId != nil {
		deferringenvironmentidVal = strconv.Itoa(*r.DeferringEnvironmentId)
	}
	executionBytes, _ := json.Marshal(r.Execution)
	executionJSON := string(executionBytes)
	forcenodeselectionVal := ""
	if r.ForceNodeSelection != nil {
		forcenodeselectionVal = strconv.FormatBool(*r.ForceNodeSelection)
	}
	jobcompletiontriggerBytes, _ := json.Marshal(r.JobCompletionTrigger)
	jobcompletiontriggerJSON := string(jobcompletiontriggerBytes)
	triggersBytes, _ := json.Marshal(r.Triggers)
	triggersJSON := string(triggersBytes)
	return []dbtCli.KeyValue{
		{Key: "ID", Value: idVal},
		{Key: "Name", Value: r.Name},
		{Key: "Description", Value: r.Description},
		{Key: "Compare Changes Flags", Value: r.CompareChangesFlags},
		{Key: "dbt Version", Value: dbtversionVal},
		{Key: "Deferring Environment ID", Value: deferringenvironmentidVal},
		{Key: "Environment ID", Value: strconv.Itoa(r.EnvironmentId)},
		{Key: "Errors On Lint Failure", Value: strconv.FormatBool(r.ErrorsOnLintFailure)},
		{Key: "Execute Steps", Value: strings.Join(r.ExecuteSteps, ", ")},
		{Key: "Execution", Value: executionJSON},
		{Key: "Force Node Selection", Value: forcenodeselectionVal},
		{Key: "Generate Docs", Value: strconv.FormatBool(r.GenerateDocs)},
		{Key: "Job Completion Trigger Condition", Value: jobcompletiontriggerJSON},
		{Key: "Job Type", Value: r.JobType},
		{Key: "Project ID", Value: strconv.Itoa(r.ProjectId)},
		{Key: "Run Compare Changes", Value: strconv.FormatBool(r.RunCompareChanges)},
		{Key: "Run Generate Sources", Value: strconv.FormatBool(r.RunGenerateSources)},
		{Key: "Run Lint", Value: strconv.FormatBool(r.RunLint)},
		{Key: "Triggers", Value: triggersJSON},
		{Key: "Triggers On Draft Pr", Value: strconv.FormatBool(r.TriggersOnDraftPR)},
	}
}

// JobCommands returns the "job" command group.
func JobCommands() *cli.Command {
	return &cli.Command{
		Name:  "job",
		Usage: "Managed a dbt Cloud job.",
		Commands: []*cli.Command{
			jobGetCommand(),
			jobListCommand(),
			jobCreateCommand(),
			jobUpdateCommand(),
		},
	}
}

func jobGetCommand() *cli.Command {
	return &cli.Command{
		Name:  "get",
		Usage: "Get a job by ID",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Job ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			result, err := client.GetJob(strconv.Itoa(int(cmd.Int("id"))))
			if err != nil {
				return fmt.Errorf("failed to get job: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				dbtCli.PrintKeyValue(jobToKeyValue(*result))
			})
		},
	}
}

func jobListCommand() *cli.Command {
	return &cli.Command{
		Name:  "list",
		Usage: "List jobs",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "Filter by project ID",
			},
			&cli.IntFlag{
				Name:  "environment-id",
				Usage: "Filter by environment ID",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			projectID := int(cmd.Int("project-id"))
			environmentID := int(cmd.Int("environment-id"))
			if projectID == 0 && environmentID == 0 {
				return fmt.Errorf("must specify --project-id or --environment-id")
			}
			if projectID != 0 && environmentID != 0 {
				return fmt.Errorf("cannot specify both --project-id and --environment-id")
			}

			client, err := getClient()
			if err != nil {
				return err
			}
			items, err := client.GetAllJobs(int(cmd.Int("project-id")), int(cmd.Int("environment-id")))
			if err != nil {
				return fmt.Errorf("failed to list jobs: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, items, func() {
				headers := []string{"ID", "Name", "Description", "Compare Changes Flags", "dbt Version", "Deferring Environment ID", "Environment ID", "Errors On Lint Failure", "Execute Steps", "Execution", "Force Node Selection", "Generate Docs", "Job Completion Trigger Condition", "Job Type", "Project ID", "Run Compare Changes", "Run Generate Sources", "Run Lint", "Triggers", "Triggers On Draft Pr"}
				rows := make([][]string, 0, len(items))
				for _, item := range items {
					rows = append(rows, jobToRow(item))
				}
				dbtCli.PrintTable(headers, rows)
			})
		},
	}
}

func jobCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create a new job",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "name",
				Usage:    "Job name",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "project-id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "environment-id",
				Usage:    "Environment ID",
				Required: true,
			},
			&cli.StringSliceFlag{
				Name:     "execute-steps",
				Usage:    "Execute steps (can be specified multiple times)",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "description",
				Usage: "Job description",
			},
			&cli.StringFlag{
				Name:  "schedule-cron",
				Usage: "Cron schedule expression",
			},
			&cli.IntFlag{
				Name:  "num-threads",
				Usage: "Number of threads",
				Value: 1,
			},
			&cli.StringFlag{
				Name:  "target-name",
				Usage: "Target name",
				Value: "default",
			},
			&cli.BoolFlag{
				Name:  "generate-docs",
				Usage: "Generate docs on run",
			},
			&cli.BoolFlag{
				Name:  "run-generate-sources",
				Usage: "Run generate sources on run",
			},
			&cli.IntFlag{
				Name:  "timeout-seconds",
				Usage: "Timeout in seconds (0 for no timeout)",
				Value: 0,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}
			triggers := map[string]any{
				"schedule":             false,
				"github_webhook":       false,
				"git_provider_webhook": false,
				"on_merge":             false,
			}
			scheduleType := "every_day"
			scheduleCron := cmd.String("schedule-cron")
			if scheduleCron != "" {
				triggers["schedule"] = true
				scheduleType = "custom_cron"
			}
			result, err := client.CreateJob(
				int(cmd.Int("project-id")),
				int(cmd.Int("environment-id")),
				cmd.String("name"),
				cmd.String("description"),
				cmd.StringSlice("execute-steps"),
				"",
				true,
				triggers,
				int(cmd.Int("num-threads")),
				cmd.String("target-name"),
				cmd.Bool("generate-docs"),
				cmd.Bool("run-generate-sources"),
				scheduleType,
				0,
				[]int{},
				[]int{},
				scheduleCron,
				0,
				0,
				false,
				int(cmd.Int("timeout-seconds")),
				false,
				nil,
				false,
				false,
				false,
				"",
				"",
				nil,
			)
			if err != nil {
				return fmt.Errorf("failed to create job: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Job created successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(jobToKeyValue(*result))
			})
		},
	}
}

func jobUpdateCommand() *cli.Command {
	return &cli.Command{
		Name:  "update",
		Usage: "Update an existing job",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Job ID",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "compare-changes-flags",
				Usage: "The model selector for checking changes in the compare changes Advanced CI feature",
			},
			&cli.StringFlag{
				Name:  "dbt-version",
				Usage: "Version number of dbt to use in this job, usually in the format 1.2.0-latest rather than core versions",
			},
			&cli.IntFlag{
				Name:  "deferring-environment-id",
				Usage: "Environment identifier that this job defers to (new deferring approach)",
			},
			&cli.StringFlag{
				Name:  "description",
				Usage: "Description for the job",
			},
			&cli.IntFlag{
				Name:  "environment-id",
				Usage: "Environment ID to create the job in",
			},
			&cli.BoolFlag{
				Name:  "errors-on-lint-failure",
				Usage: "Whether the CI job should fail when a lint error is found. Only used when `run_lint` is set to `true`. Defaults to `true`.",
			},
			&cli.StringSliceFlag{
				Name:  "execute-steps",
				Usage: "List of commands to execute for the job",
			},
			&cli.IntFlag{
				Name:  "execution-timeout-seconds",
				Usage: "The number of seconds before the job times out",
			},
			&cli.BoolFlag{
				Name:  "generate-docs",
				Usage: "Flag for whether the job should generate documentation",
			},
			&cli.StringFlag{
				Name:  "job-type",
				Usage: "Can be used to enforce the job type betwen `ci`, `merge` and `scheduled`. Without this value the job type is inferred from the triggers configured",
			},
			&cli.StringFlag{
				Name:  "name",
				Usage: "Job name",
			},
			&cli.IntFlag{
				Name:  "project-id",
				Usage: "Project ID to create the job in",
			},
			&cli.BoolFlag{
				Name:  "run-compare-changes",
				Usage: "Whether the CI job should compare data changes introduced by the code changes. Requires `deferring_environment_id` to be set. (Advanced CI needs to be activated in the dbt Cloud Account Settings first as well)",
			},
			&cli.BoolFlag{
				Name:  "run-generate-sources",
				Usage: "Flag for whether the job should add a `dbt source freshness` step to the job. The difference between manually adding a step with `dbt source freshness` in the job steps or using this flag is that with this flag, a failed freshness will still allow the following steps to run.",
			},
			&cli.BoolFlag{
				Name:  "run-lint",
				Usage: "Whether the CI job should lint SQL changes. Defaults to `false`.",
			},
			&cli.BoolFlag{
				Name:  "triggers-git-provider-webhook",
				Usage: "Whether the job runs automatically on PR creation",
			},
			&cli.BoolFlag{
				Name:  "triggers-github-webhook",
				Usage: "Whether the job runs automatically on PR creation",
			},
			&cli.BoolFlag{
				Name:  "triggers-on-merge",
				Usage: "Whether the job runs automatically once a PR is merged",
			},
			&cli.BoolFlag{
				Name:  "triggers-schedule",
				Usage: "Whether the job runs on a schedule",
			},
			&cli.BoolFlag{
				Name:  "triggers-on-draft-pr",
				Usage: "Whether the CI job should be automatically triggered on draft PRs",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			id := strconv.Itoa(int(cmd.Int("id")))

			existing, err := client.GetJob(id)
			if err != nil {
				return fmt.Errorf("failed to get job: %w", err)
			}
			if v := cmd.String("compare-changes-flags"); v != "" {
				existing.CompareChangesFlags = v
			}
			if cmd.IsSet("dbt-version") {
				v := cmd.String("dbt-version")
				existing.DbtVersion = &v
			}
			if cmd.IsSet("deferring-environment-id") {
				v := int(cmd.Int("deferring-environment-id"))
				existing.DeferringEnvironmentId = &v
			}
			if v := cmd.String("description"); v != "" {
				existing.Description = v
			}
			if v := int(cmd.Int("environment-id")); v != 0 {
				existing.EnvironmentId = v
			}
			if cmd.IsSet("errors-on-lint-failure") {
				existing.ErrorsOnLintFailure = cmd.Bool("errors-on-lint-failure")
			}
			if cmd.IsSet("execute-steps") {
				existing.ExecuteSteps = cmd.StringSlice("execute-steps")
			}
			if v := int(cmd.Int("execution-timeout-seconds")); v != 0 {
				existing.Execution.TimeoutSeconds = v
			}
			if cmd.IsSet("generate-docs") {
				existing.GenerateDocs = cmd.Bool("generate-docs")
			}
			if v := cmd.String("job-type"); v != "" {
				existing.JobType = v
			}
			if v := cmd.String("name"); v != "" {
				existing.Name = v
			}
			if v := int(cmd.Int("project-id")); v != 0 {
				existing.ProjectId = v
			}
			if cmd.IsSet("run-compare-changes") {
				existing.RunCompareChanges = cmd.Bool("run-compare-changes")
			}
			if cmd.IsSet("run-generate-sources") {
				existing.RunGenerateSources = cmd.Bool("run-generate-sources")
			}
			if cmd.IsSet("run-lint") {
				existing.RunLint = cmd.Bool("run-lint")
			}
			if cmd.IsSet("triggers-git-provider-webhook") {
				existing.Triggers.GitProviderWebhook = cmd.Bool("triggers-git-provider-webhook")
			}
			if cmd.IsSet("triggers-github-webhook") {
				existing.Triggers.GithubWebhook = cmd.Bool("triggers-github-webhook")
			}
			if cmd.IsSet("triggers-on-merge") {
				existing.Triggers.OnMerge = cmd.Bool("triggers-on-merge")
			}
			if cmd.IsSet("triggers-schedule") {
				existing.Triggers.Schedule = cmd.Bool("triggers-schedule")
			}
			if cmd.IsSet("triggers-on-draft-pr") {
				existing.TriggersOnDraftPR = cmd.Bool("triggers-on-draft-pr")
			}

			result, err := client.UpdateJob(id, *existing)
			if err != nil {
				return fmt.Errorf("failed to update job: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Job updated successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(jobToKeyValue(*result))
			})
		},
	}
}
