// Code generated by dbtp codegen. DO NOT EDIT.
package commands

import (
	"context"
	"fmt"
	"strconv"

	dbtCli "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/cli"
	dbtcloud "github.com/dbt-labs/terraform-provider-dbtcloud/pkg/dbt_cloud"
	"github.com/urfave/cli/v3"
)

// projectToRow converts a ProjectConnectionRepository to a table row.
func projectToRow(r dbtcloud.ProjectConnectionRepository) []string {
	freshnessjobidVal := ""
	if r.FreshnessJobID != nil {
		freshnessjobidVal = strconv.FormatInt(*r.FreshnessJobID, 10)
	}
	docsjobidVal := ""
	if r.DocsJobID != nil {
		docsjobidVal = strconv.FormatInt(*r.DocsJobID, 10)
	}
	return []string{
		strconv.FormatInt(r.ID, 10),
		r.Name,
		r.Description,
		r.DbtProjectSubdirectory,
		strconv.FormatInt(r.DbtProjectType, 10),
		strconv.FormatInt(r.ConnectionID, 10),
		strconv.FormatInt(r.RepositoryID, 10),
		freshnessjobidVal,
		docsjobidVal,
	}
}

// projectToKeyValue converts a Project to key-value pairs for detailed display.
func projectToKeyValue(r dbtcloud.Project) []dbtCli.KeyValue {
	idVal := ""
	if r.ID != nil {
		idVal = strconv.Itoa(*r.ID)
	}
	dbtprojectsubdirectoryVal := ""
	if r.DbtProjectSubdirectory != nil {
		dbtprojectsubdirectoryVal = *r.DbtProjectSubdirectory
	}
	connectionidVal := ""
	if r.ConnectionID != nil {
		connectionidVal = strconv.Itoa(*r.ConnectionID)
	}
	repositoryidVal := ""
	if r.RepositoryID != nil {
		repositoryidVal = strconv.Itoa(*r.RepositoryID)
	}
	freshnessjobidVal := ""
	if r.FreshnessJobId != nil {
		freshnessjobidVal = strconv.Itoa(*r.FreshnessJobId)
	}
	docsjobidVal := ""
	if r.DocsJobId != nil {
		docsjobidVal = strconv.Itoa(*r.DocsJobId)
	}
	return []dbtCli.KeyValue{
		{Key: "ID", Value: idVal},
		{Key: "Name", Value: r.Name},
		{Key: "Description", Value: r.Description},
		{Key: "Subdirectory", Value: dbtprojectsubdirectoryVal},
		{Key: "Type", Value: strconv.FormatInt(r.DbtProjectType, 10)},
		{Key: "Connection ID", Value: connectionidVal},
		{Key: "Repository ID", Value: repositoryidVal},
		{Key: "Freshness Job ID", Value: freshnessjobidVal},
		{Key: "Docs Job ID", Value: docsjobidVal},
	}
}

// ProjectCommands returns the "project" command group.
func ProjectCommands() *cli.Command {
	return &cli.Command{
		Name:  "project",
		Usage: "Manages a dbt Cloud project.",
		Commands: []*cli.Command{
			projectGetCommand(),
			projectListCommand(),
			projectCreateCommand(),
			projectUpdateCommand(),
		},
	}
}

func projectGetCommand() *cli.Command {
	return &cli.Command{
		Name:  "get",
		Usage: "Get a project by ID",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Project ID",
				Required: true,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			result, err := client.GetProject(strconv.Itoa(int(cmd.Int("id"))))
			if err != nil {
				return fmt.Errorf("failed to get project: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				dbtCli.PrintKeyValue(projectToKeyValue(*result))
			})
		},
	}
}

func projectListCommand() *cli.Command {
	return &cli.Command{
		Name:  "list",
		Usage: "List projects",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "name-contains",
				Usage: "Used to filter projects by name, Optional",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {

			client, err := getClient()
			if err != nil {
				return err
			}
			items, err := client.GetAllProjects(cmd.String("name-contains"))
			if err != nil {
				return fmt.Errorf("failed to list projects: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, items, func() {
				headers := []string{"ID", "Name", "Description", "Subdirectory", "Type", "Connection ID", "Repository ID", "Freshness Job ID", "Docs Job ID"}
				rows := make([][]string, 0, len(items))
				for _, item := range items {
					rows = append(rows, projectToRow(item))
				}
				dbtCli.PrintTable(headers, rows)
			})
		},
	}
}

func projectCreateCommand() *cli.Command {
	return &cli.Command{
		Name:  "create",
		Usage: "Create a new project",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "name",
				Usage:    "Project name",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "description",
				Usage: "Description for the project. Will show in dbt Explorer.",
			},
			&cli.StringFlag{
				Name:  "dbt-project-subdirectory",
				Usage: "DBT project subdirectory",
			},
			&cli.IntFlag{
				Name:  "dbt-project-type",
				Usage: "The type of dbt project (0=default or 1=hybrid)",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}
			result, err := client.CreateProject(cmd.String("name"), cmd.String("description"), cmd.String("dbt-project-subdirectory"), int64(cmd.Int("dbt-project-type")))
			if err != nil {
				return fmt.Errorf("failed to create project: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Project created successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(projectToKeyValue(*result))
			})
		},
	}
}

func projectUpdateCommand() *cli.Command {
	return &cli.Command{
		Name:  "update",
		Usage: "Update an existing project",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:     "id",
				Usage:    "Project ID",
				Required: true,
			},
			&cli.StringFlag{
				Name:  "dbt-project-subdirectory",
				Usage: "DBT project subdirectory",
			},
			&cli.StringFlag{
				Name:  "description",
				Usage: "Description for the project. Will show in dbt Explorer.",
			},
			&cli.StringFlag{
				Name:  "name",
				Usage: "Project name",
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			client, err := getClient()
			if err != nil {
				return err
			}

			id := strconv.Itoa(int(cmd.Int("id")))

			existing, err := client.GetProject(id)
			if err != nil {
				return fmt.Errorf("failed to get project: %w", err)
			}
			if cmd.IsSet("dbt-project-subdirectory") {
				v := cmd.String("dbt-project-subdirectory")
				existing.DbtProjectSubdirectory = &v
			}
			if v := cmd.String("description"); v != "" {
				existing.Description = v
			}
			if v := cmd.String("name"); v != "" {
				existing.Name = v
			}

			result, err := client.UpdateProject(id, *existing)
			if err != nil {
				return fmt.Errorf("failed to update project: %w", err)
			}

			format := getFormat(cmd)
			return dbtCli.FormatOutput(format, result, func() {
				fmt.Println(dbtCli.SuccessStyle().Render("Project updated successfully!"))
				fmt.Println()
				dbtCli.PrintKeyValue(projectToKeyValue(*result))
			})
		},
	}
}
